### PR TITLE
got move item functionality working

### PR DESCRIPTION
**Pull request by zbhuiyan**

### CODE REVIEW

**Comment by jenwei** [comment]
@zbhuiyan - seems like you also pushed something for a `deleteItem` button - is that already implemented/are you also working on that?

LGTM though!

CC: @adeaver + @jovanduy - want to do a second lookover and merge?

**Comment by zbhuiyan** [comment]
@jenwei my last pull request was the delete items and edit items buttons. Everything seemed to work but im sure can be made better~

**Comment by adeaver** [comment]
This isn't working for me. It keeps saying "Cannot read property 'x' of null"

**Comment by adeaver** [comment]
Also, do we know that the persistence layer will be able to handle this?

**Comment by jenwei** [comment]
@adeaver - ahh forgot about that 

unsure about that - probably won't be able to check it tonight unfortunately :/

**Comment by zbhuiyan** [comment]
Oh the reason it says that is because we have to click exactly on the points for the line. It's easier for the shapes with more points. I'm not sure how to fix that -tolerance? I'll look into it more and submit another pull req.

Sent from my T-Mobile 4G LTE Device

Update: So JWei and I thought it best to just comment out edit Items for now (bc it's not that important) and add it in later if the tolerance thing works.

-------- Original message --------

**Pull request closed without merging**
